import re
from pathlib import Path

from ks_gen.loader import load_host_config
from ks_gen.writer import build_bundle


def _normalize(text: str) -> str:
    text = re.sub(r"Generated by ks-gen v\S+ on \S+", "Generated by ks-gen vSNAP on SNAP", text)
    text = re.sub(r"Generated: \S+", "Generated: SNAP", text)
    text = re.sub(r'<xccdf:version time="[^"]+"', '<xccdf:version time="SNAP"', text)
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def test_luks_partial_inline_snapshot(snapshot):
    yaml_path = Path(__file__).parent / "luks-partial-inline.host.yaml"
    bundle = build_bundle(load_host_config(yaml_path, sets=[]))
    assert _normalize(bundle.ks_cfg) == snapshot(name="ks.cfg")


def test_luks_partial_inline_pv_encrypted():
    yaml_path = Path(__file__).parent / "luks-partial-inline.host.yaml"
    bundle = build_bundle(load_host_config(yaml_path, sets=[]))
    ks = bundle.ks_cfg
    pv_lines = [
        re.sub(r"\s+", " ", line.strip())
        for line in ks.splitlines()
        if line.strip().startswith("part pv.01")
    ]
    assert len(pv_lines) == 1
    assert (
        pv_lines[0]
        == 'part pv.01 --grow --size=1 --encrypted --luks-version=luks2 --passphrase="hunter2"'
    )


def test_luks_partial_inline_boot_not_encrypted():
    yaml_path = Path(__file__).parent / "luks-partial-inline.host.yaml"
    bundle = build_bundle(load_host_config(yaml_path, sets=[]))
    ks = bundle.ks_cfg
    boot_lines = [
        line
        for line in ks.splitlines()
        if line.startswith("part /boot/efi") or line.startswith("part /boot ")
    ]
    assert len(boot_lines) == 2
    for line in boot_lines:
        assert "--encrypted" not in line


def test_luks_partial_inline_no_tang_post_block():
    yaml_path = Path(__file__).parent / "luks-partial-inline.host.yaml"
    bundle = build_bundle(load_host_config(yaml_path, sets=[]))
    ks = bundle.ks_cfg
    assert "clevis luks bind" not in ks
    assert "clevis-luks-askpass" not in ks
