import re
from pathlib import Path

from ks_gen.loader import load_host_config
from ks_gen.writer import build_bundle


def _normalize(text: str) -> str:
    text = re.sub(r"Generated by ks-gen v\S+ on \S+", "Generated by ks-gen vSNAP on SNAP", text)
    text = re.sub(r"Generated: \S+", "Generated: SNAP", text)
    text = re.sub(r'<xccdf:version time="[^"]+"', '<xccdf:version time="SNAP"', text)
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def test_luks_tang_snapshot(snapshot):
    yaml_path = Path(__file__).parent / "luks-tang.host.yaml"
    bundle = build_bundle(load_host_config(yaml_path, sets=[]))
    assert _normalize(bundle.ks_cfg) == snapshot(name="ks.cfg")


def test_luks_tang_pv_encrypted_with_fallback_passphrase():
    yaml_path = Path(__file__).parent / "luks-tang.host.yaml"
    bundle = build_bundle(load_host_config(yaml_path, sets=[]))
    ks = bundle.ks_cfg
    pv_lines = [
        re.sub(r"\s+", " ", line.strip())
        for line in ks.splitlines()
        if line.strip().startswith("part pv.01")
    ]
    assert len(pv_lines) == 1
    assert "--encrypted --luks-version=luks2" in pv_lines[0]
    assert '--passphrase="fallback"' in pv_lines[0]


def test_luks_tang_post_block_present():
    yaml_path = Path(__file__).parent / "luks-tang.host.yaml"
    bundle = build_bundle(load_host_config(yaml_path, sets=[]))
    ks = bundle.ks_cfg
    assert "dnf -y install clevis clevis-luks clevis-systemd" in ks
    assert 'clevis luks bind -d "$luks_dev" -y sss' in ks
    assert "systemctl enable clevis-luks-askpass.path" in ks


def test_luks_tang_post_block_has_both_servers_and_thumbprints():
    yaml_path = Path(__file__).parent / "luks-tang.host.yaml"
    bundle = build_bundle(load_host_config(yaml_path, sets=[]))
    ks = bundle.ks_cfg
    assert '"url": "https://tang1.example.com"' in ks
    assert '"url": "https://tang2.example.com"' in ks
    assert '"thp": "xK3HFGm-AVOaJVlA8oFAo7uMcrJBhFCdwq8WX8gqXJU"' in ks
    assert '"thp": "yL4IGHn-BWPbKWmA9pBp8vNdsKChiGDexr9XY9hrYKV"' in ks
    assert '"t": 1' in ks
