import re
from pathlib import Path

from ks_gen.loader import load_host_config
from ks_gen.writer import build_bundle


def _normalize(text: str) -> str:
    text = re.sub(r"Generated by ks-gen v\S+ on \S+", "Generated by ks-gen vSNAP on SNAP", text)
    text = re.sub(r"Generated: \S+", "Generated: SNAP", text)
    text = re.sub(r'<xccdf:version time="[^"]+"', '<xccdf:version time="SNAP"', text)
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def _partitioning_lines(ks_cfg: str) -> list[str]:
    """Extract part/volgroup/logvol lines and collapse internal whitespace."""
    lines = []
    for raw in ks_cfg.splitlines():
        stripped = raw.strip()
        if stripped.startswith(("part ", "volgroup ", "logvol ")):
            # Collapse runs of whitespace to a single space.
            lines.append(re.sub(r"\s+", " ", stripped))
    return lines


def test_layout_stig_baseline_equivalent_to_preset(snapshot):
    layout_yaml = Path(__file__).parent / "layout-stig-baseline.host.yaml"
    preset_yaml = Path(__file__).parent / "layout-stig-baseline-preset.host.yaml"
    layout_bundle = build_bundle(load_host_config(layout_yaml, sets=[]))
    preset_bundle = build_bundle(load_host_config(preset_yaml, sets=[]))

    layout_part = _partitioning_lines(layout_bundle.ks_cfg)
    preset_part = _partitioning_lines(preset_bundle.ks_cfg)

    assert layout_part == preset_part, (
        "Layout-rendered partitioning must match preset-rendered "
        "partitioning after whitespace normalization. Diff:\n"
        f"  layout: {layout_part}\n  preset: {preset_part}"
    )


def test_layout_stig_baseline_snapshot(snapshot):
    layout_yaml = Path(__file__).parent / "layout-stig-baseline.host.yaml"
    bundle = build_bundle(load_host_config(layout_yaml, sets=[]))
    assert _normalize(bundle.ks_cfg) == snapshot(name="ks.cfg")
