import re
from pathlib import Path

from ks_gen.loader import load_host_config
from ks_gen.writer import build_bundle


def _normalize(text: str) -> str:
    text = re.sub(r"Generated by ks-gen v\S+ on \S+", "Generated by ks-gen vSNAP on SNAP", text)
    text = re.sub(r"Generated: \S+", "Generated: SNAP", text)
    text = re.sub(r'<xccdf:version time="[^"]+"', '<xccdf:version time="SNAP"', text)
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def test_alma10_minimal(snapshot):
    yaml_path = Path(__file__).parent / "alma10-minimal.host.yaml"
    cfg = load_host_config(yaml_path, sets=[])
    bundle = build_bundle(cfg)
    # alma10 bundle shape matches alma9/alma8: ks_cfg required, no cloud-init.
    assert bundle.ks_cfg is not None
    assert bundle.user_data is None
    assert bundle.meta_data is None
    assert _normalize(bundle.ks_cfg) == snapshot(name="ks.cfg")
    assert _normalize(bundle.tailoring_xml) == snapshot(name="tailoring.xml")
    assert _normalize(bundle.exceptions_md) == snapshot(name="exceptions.md")
    assert _normalize(bundle.host_yaml) == snapshot(name="host.yaml")


def test_alma10_tailoring_points_at_al10_datastream():
    cfg = load_host_config(Path(__file__).parent / "alma10-minimal.host.yaml", sets=[])
    assert cfg.meta.scap_content == "ssg-almalinux10-ds.xml"
    assert "ssg-almalinux10-ds.xml" in build_bundle(cfg).ks_cfg
