import re
from pathlib import Path

from ks_gen.loader import load_host_config
from ks_gen.writer import build_bundle


def _normalize(text: str) -> str:
    text = re.sub(r"Generated by ks-gen v\S+ on \S+", "Generated by ks-gen vSNAP on SNAP", text)
    text = re.sub(r"Generated: \S+", "Generated: SNAP", text)
    text = re.sub(r'<xccdf:version time="[^"]+"', '<xccdf:version time="SNAP"', text)
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def test_layout_custom_sizes(snapshot):
    yaml_path = Path(__file__).parent / "layout-custom-sizes.host.yaml"
    bundle = build_bundle(load_host_config(yaml_path, sets=[]))
    assert _normalize(bundle.ks_cfg) == snapshot(name="ks.cfg")


def test_layout_custom_sizes_ondisk_emitted_on_all_three_partitions():
    yaml_path = Path(__file__).parent / "layout-custom-sizes.host.yaml"
    bundle = build_bundle(load_host_config(yaml_path, sets=[]))
    ks = bundle.ks_cfg
    lines = ks.splitlines()
    # All three install-partitioning lines must carry --ondisk=sda.
    efi_line = next(line for line in lines if "part /boot/efi" in line)
    assert "--ondisk=sda" in efi_line
    boot_line = next(line for line in lines if line.startswith("part /boot "))
    assert "--ondisk=sda" in boot_line
    pv_line = next(line for line in lines if "part pv.01" in line)
    assert "--ondisk=sda" in pv_line


def test_layout_custom_sizes_explicit_sizes_used():
    yaml_path = Path(__file__).parent / "layout-custom-sizes.host.yaml"
    bundle = build_bundle(load_host_config(yaml_path, sets=[]))
    ks = bundle.ks_cfg
    # /var was set to 20G -> 20480, /var/log to 10G -> 10240, /srv 50G -> 51200
    assert "logvol /var --vgname=vg_root --name=var --fstype=xfs --size=20480" in ks
    assert "logvol /var/log --vgname=vg_root --name=varlog --fstype=xfs --size=10240" in ks
    srv_expected = (
        "logvol /srv --vgname=vg_root --name=srv --fstype=xfs"
        ' --size=51200 --fsoptions="nodev,nosuid"'
    )
    assert srv_expected in ks
