import re
from pathlib import Path

from ks_gen.loader import load_host_config
from ks_gen.writer import build_bundle


def _normalize(text: str) -> str:
    text = re.sub(r"Generated by ks-gen v\S+ on \S+", "Generated by ks-gen vSNAP on SNAP", text)
    text = re.sub(r"Generated: \S+", "Generated: SNAP", text)
    text = re.sub(r'<xccdf:version time="[^"]+"', '<xccdf:version time="SNAP"', text)
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def test_data_disks_wipe(snapshot):
    yaml_path = Path(__file__).parent / "data-disks-wipe.host.yaml"
    bundle = build_bundle(load_host_config(yaml_path, sets=[]))
    assert _normalize(bundle.ks_cfg) == snapshot(name="ks.cfg")
