import re
from pathlib import Path

from ks_gen.loader import load_host_config
from ks_gen.writer import build_bundle


def _normalize(text: str) -> str:
    text = re.sub(r"Generated by ks-gen v\S+ on \S+", "Generated by ks-gen vSNAP on SNAP", text)
    text = re.sub(r"Generated: \S+", "Generated: SNAP", text)
    text = re.sub(r'<xccdf:version time="[^"]+"', '<xccdf:version time="SNAP"', text)
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


# The yaml fixture's passphrase_file uses a path relative to the project
# root (tests/golden/luks-partial-sidecar.key). Pin cwd to the project
# root so resolution is deterministic regardless of where pytest is run.
_REPO_ROOT = Path(__file__).parent.parent.parent


def test_luks_partial_sidecar_renders_passphrase_from_file(monkeypatch):
    monkeypatch.chdir(_REPO_ROOT)
    yaml_path = Path(__file__).parent / "luks-partial-sidecar.host.yaml"
    bundle = build_bundle(load_host_config(yaml_path, sets=[]))
    ks = bundle.ks_cfg
    pv_lines = [
        re.sub(r"\s+", " ", line.strip())
        for line in ks.splitlines()
        if line.strip().startswith("part pv.01")
    ]
    assert len(pv_lines) == 1
    assert (
        pv_lines[0]
        == 'part pv.01 --grow --size=1 --encrypted --luks-version=luks2 --passphrase="sidecartest"'
    )


def test_luks_partial_sidecar_snapshot(monkeypatch, snapshot):
    monkeypatch.chdir(_REPO_ROOT)
    yaml_path = Path(__file__).parent / "luks-partial-sidecar.host.yaml"
    bundle = build_bundle(load_host_config(yaml_path, sets=[]))
    assert _normalize(bundle.ks_cfg) == snapshot(name="ks.cfg")
