import re
from pathlib import Path

from ks_gen.loader import load_host_config
from ks_gen.writer import build_bundle


def _normalize(text: str) -> str:
    text = re.sub(r"Generated by ks-gen v\S+ on \S+", "Generated by ks-gen vSNAP on SNAP", text)
    text = re.sub(r"Generated: \S+", "Generated: SNAP", text)
    text = re.sub(r'<xccdf:version time="[^"]+"', '<xccdf:version time="SNAP"', text)
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def test_ubuntu_minimal(snapshot):
    yaml_path = Path(__file__).parent / "ubuntu-minimal.host.yaml"
    cfg = load_host_config(yaml_path, sets=[])
    bundle = build_bundle(cfg)
    assert bundle.user_data is not None
    assert bundle.meta_data is not None
    assert _normalize(bundle.user_data) == snapshot(name="user-data")
    assert _normalize(bundle.meta_data) == snapshot(name="meta-data")
    assert _normalize(bundle.tailoring_xml) == snapshot(name="tailoring.xml")
    assert _normalize(bundle.exceptions_md) == snapshot(name="exceptions.md")
    assert _normalize(bundle.host_yaml) == snapshot(name="host.yaml")
