from __future__ import annotations

from collections.abc import Iterable
from datetime import UTC, datetime

from ks_gen.rules._types import TailoringOp

# The profile id the tailoring defines. oscap evaluates whatever `--profile`
# names, so every caller must pass THIS id, not the base profile it extends —
# passing the base silently evaluates the untailored profile (#65).
TAILORED_PROFILE_ID = "xccdf_ks-gen_profile_tailored"

_BASE_PROFILE_PREFIX = "xccdf_org.ssgproject.content_profile_"


def base_profile_id(profile: str) -> str:
    """The SSG profile the tailoring extends, e.g. `stig` -> the full id.

    One definition so the gen and verify sides cannot compute it differently
    and produce spurious tailoring-drift.
    """
    return f"{_BASE_PROFILE_PREFIX}{profile}"


_HEADER = (
    "<?xml version='1.0' encoding='UTF-8'?>\n"
    '<xccdf:Tailoring xmlns:xccdf="http://checklists.nist.gov/xccdf/1.2" '
    'id="xccdf_ks-gen_tailoring_default">\n'
    '  <xccdf:benchmark href="/usr/share/xml/scap/ssg/content/{scap_content}"/>\n'
    '  <xccdf:version time="{timestamp}">1</xccdf:version>\n'
    f'  <xccdf:Profile id="{TAILORED_PROFILE_ID}" extends="{{profile_id}}">\n'
    '    <xccdf:title xml:lang="en-US">ks-gen tailored {profile_id}</xccdf:title>\n'
    '    <xccdf:description xml:lang="en-US">Tailoring generated by ks-gen.</xccdf:description>\n'
)

_FOOTER = "  </xccdf:Profile>\n</xccdf:Tailoring>\n"


def build_tailoring_xml(ops: Iterable[TailoringOp], *, profile_id: str, scap_content: str) -> str:
    body: list[str] = []
    for op in ops:
        if op.action == "disable":
            body.append(f'    <xccdf:select idref="{op.rule_id}" selected="false"/>')
        elif op.action == "select":
            body.append(f'    <xccdf:select idref="{op.rule_id}" selected="true"/>')
        elif op.action == "set_value":
            value = "" if op.value is None else _escape(op.value)
            body.append(f'    <xccdf:set-value idref="{op.rule_id}">{value}</xccdf:set-value>')
    head = _HEADER.format(
        timestamp=datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        profile_id=profile_id,
        scap_content=scap_content,
    )
    return head + ("\n".join(body) + "\n" if body else "") + _FOOTER


def _escape(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")
